name: Enrich Data
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */6 * * *" 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install Jupyter
      run: |
        pip install jupyter
        pip install -r requirements.txt 
    - name: Run Notebook
      env:
        GH_TOKEN:  ${{ secrets.ORG_REPO_TOKEN }}
      run: |
         jupyter nbconvert --to notebook --execute cisa_enriched.ipynb
         jupyter nbconvert --to html --TemplateExporter.exclude_input=True --no-prompt cisa_enriched.nbconvert.ipynb --output index.html
         rm index.html
         rm cisa_enriched.nbconvert.ipynb 
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: KhulnaSoft DevOps
        message: "Update CVE Reports"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
